name: Zadanie 2 - Pipeline CI/CD

on:
  push:
    branches: [ main ] # Uruchomienie automatyczne po wrzuceniu kodu na gałąź main

jobs:
  build-and-secure-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie kodu źródłowego
        uses: actions/checkout@v4

      - name: Konfiguracja QEMU
        uses: docker/setup-qemu-action@v3

      - name: Konfiguracja Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Logowanie do Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Logowanie do GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Budowanie lokalnego obrazu do testu CVE
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ghcr.io/${{ github.repository }}:test

      - name: Skanowanie obrazu narzędziem Trivy (Test CVE)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository }}:test'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'

      - name: Budowanie docelowe i publikacja (Multi-arch + Cache Max)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/zadanie2-cache:latest
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/zadanie2-cache:latest,mode=max,oci-mediatypes=false,compression=gzip